#! /bin/bash

PYTHON=$(which python3)
SUPER=$(realpath super-resolution.py)
STATS=$(realpath statistics.py)
OUTDIR=./denoised
IMAGES_DIR=../../images/

# move to images directory
pushd ${IMAGES_DIR}

# if the output directory does not exist, create it
if [ ! -d ${OUTDIR} ]; then
    mkdir ${OUTDIR}
fi

# perform filtering
for image in *_noisy?.png; do
    truth=$(echo ${image} | sed "s/noisy./truth/")
    for filter in gaussian median improved_median bilateral; do
	filename=${image%.*}
	output=${OUTDIR}/${filename}_${filter}.png

	# execute super resolution
	SUPER_COMMAND="${PYTHON} ${SUPER} ${image} -k ${filter} -o ${output}"
	echo ${SUPER_COMMAND}
	${SUPER_COMMAND}

	# execute statistics
	STATS_COMMAND="${PYTHON} ${STATS} ${output} ${truth} --snr --log-snr --rmse"
	echo ${STATS_COMMAND}
	${STATS_COMMAND}
    done
done

# move back to execution directory
popd
